test:
	g++ -o test test.cpp L1cache.cpp Mem.cpp
	@echo "compiling test.cpp"
	@echo "compiling L1cache.cpp"
	@echo "compiling Mem.cpp"

quick:
	g++ -o quicksort quicksort.cpp L1cache.cpp Mem.cpp
	@echo "compiling quicksort.cpp"
	@echo "compiling L1cache.cpp"
	@echo "compiling Mem.cpp"

merge:
	g++ -o mergesort mergesort.cpp L1cache.cpp Mem.cpp
	@echo "compiling mergesort.cpp..."
	@echo "compiling L1cache.cpp..."
	@echo "compiling Mem.cpp"

clean:
	rm -f test quicksort mergesort
	@echo "removing test..."
	@echo "removing quicksort..."
	@echo "removing mergesort..."
